<?php

########################################################################
# Extension Manager/Repository config file for ext: "ws_questionnaire"
#
# Auto generated by Extension Builder 2012-09-22
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = [
	'title' => 'Questionnaire',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Sven Wappler',
	'author_email' => 'typo3YYYY@wappler.systems',
	'author_company' => 'www.wappler.systems',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => [
		'depends' => [
			'typo3' => '8.7.0-8.9.99',
        ],
		'conflicts' => [
        ],
		'suggests' => [
        ],
    ],
];

