<?php

########################################################################
# Extension Manager/Repository config file for ext: "ke_questionnaire"
#
# Auto generated by Extension Builder 2012-09-22
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = [
	'title' => 'Questionnaire',
	'description' => 'SEE https://www.pivotaltracker.com/story/show/132754271 !! Easily create any type of questionnaire, survey, poll, quiz or eLearning. The results may be evaluated and displayed graphically at any time. See further information - also about the premium version - at www.ke-questionnaire.de',
	'category' => 'plugin',
	'author' => 'kennziffer.com',
	'author_email' => 'info@kennziffer.com',
	'author_company' => 'www.kennziffer.com',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '8.7.5.sw',
	'constraints' => [
		'depends' => [
			'typo3' => '8.7.0-8.9.99',
        ],
		'conflicts' => [
        ],
		'suggests' => [
        ],
    ],
];

?>